
### Obtener usuarios
DELETE  http://localhost:3000/api/v1/categories/delete/2
Content-Type: application/json


### Crear un usuario
GET http://localhost:3000/api/v1/encabezados/all
Content-Type: application/json



### actualizar un usuario
PUT http://localhost:3000//api/v1/encabezado/update/

    {
      "username": "jairo manue",
      "password": "new_password",
      "apellido": "New Doe",
      "telefono": "987654321"
    }

### eliminar un usuario

DELETE  http://localhost:3000/users/12
  

