
### Obtener usuarios
DELETE  http://localhost:3000/api/v1/categories/delete/2
Content-Type: application/json


### Crear un usuario
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "Ema_User": "yoinerpertuz@gmail.com",
    "Pass_User": "1234567890",
    "Dir_Ip": "192.168.0.1"
    
}


### Crear un usuario
PUT http://localhost:3000/users/update/12

    {
      "username": "jairo manue",
      "password": "new_password",
      "apellido": "New Doe",
      "telefono": "987654321"
    }

### eliminar un usuario

DELETE  http://localhost:3000/users/12
  

